from enum import StrEnum


class ReasonCode(StrEnum):
    PII_DETECTED_OUTPUT = "PII_DETECTED_OUTPUT"
    PII_DETECTED_INPUT = "PII_DETECTED_INPUT"
    CLAIM_UNSUPPORTED = "CLAIM_UNSUPPORTED"
    CLAIM_CONTRADICTED = "CLAIM_CONTRADICTED"
    CLAIM_SUPPORTED = "CLAIM_SUPPORTED"
    NUMERIC_MISMATCH = "NUMERIC_MISMATCH"
    NUMERIC_VERIFIED = "NUMERIC_VERIFIED"
    HIGH_DISAGREEMENT = "HIGH_DISAGREEMENT"
    EVIDENCE_UNAVAILABLE = "EVIDENCE_UNAVAILABLE"
    CASCADE_RISK_ELEVATED = "CASCADE_RISK_ELEVATED"
    ACTION_BLAST_RADIUS_HIGH = "ACTION_BLAST_RADIUS_HIGH"
    POLICY_VERSION_STALE = "POLICY_VERSION_STALE"
    INJECTION_SUSPECTED = "INJECTION_SUSPECTED"
    HUMAN_OVERRIDE = "HUMAN_OVERRIDE"

